baseURL = "https://bdl-belmont.tfcow.workers.dev/"
title = "BDL Belmont"
locale = "fr-FR"
defaultContentLanguage = "fr"

buildFuture = true
disableKinds = ["taxonomy", "term"]

[menus]
  [[menus.main]]
    name = "Accueil"
    url = "/"
    weight = 1
  [[menus.main]]
    name = "Actus"
    url = "/actus/"
    weight = 2
  [[menus.main]]
    name = "Événements"
    url = "/evenements/"
    weight = 3
  [[menus.main]]
    name = "Le bureau"
    url = "/bureau/"
    weight = 4

[params]
  mainSections = ["actus", "evenements"]

# Remplacement de la virgule par un point ici :
[params.theme]
  defaultTheme = "light"
  disableThemeToggle = false

  # Accueil
  title = "BDL Belmont"
  description = "La vie étudiante à Belmont"